theme: "harbor"
baseURL: https://joshmills.blog/
languageCode: en-us
title: Josh M's Blog
params:
  social:
    - name: LinkedIn
      url: https://www.linkedin.com/in/joshuajohnmills/
      icon: <i class="fa-brands fa-linkedin"></i>
  logo:
    url: icon.png
    width: 50
    height: 50
    alt: Logo
