---
title: Teamfight Tactics solved as a MIP with mip-python
author: Josh M
date: '2022-07-31'
slug: []
categories:
  - Python
  - Optimisation
tags:
  - ''
backtotop: no
draft: no
toc: no
---

## Teamfight Tactics

<!-- toc -->

Teamfight tactics is an auto battler game. You play as a "tiny titan" who builds a team of champions to fight on their bidding in a round robin against 7 other players. Each time you lose a battle your titan takes some damage until eventually you are eliminated. If you are the last titan standing then you win the round.

Central building an army are synergies. All of the champions you can choose from have two or three "traits". Putting champions that share a trait together will give you a bonus. Some traits require only a single champion to become active, but most activate, and then power up at set numbers of champions such as 3,5, and 7. For example if you have 


While this gives a brief overview, there are certainly better explanations than this online, but the best way to understand it is to play the game yourself. It will be difficult to appreciate the content in the blog post if you have never played TFT however I will attempt to clarify some terms to make it easier. 

In this program I have written a script that when run will suggest a team composition that can satisfy various constraints, such as not having "hanging traits", having a certain combination of traits, maximizing the price of your team while having no active traits and so on based on a data input file. 

We can also consider augments and spatula items that 

## Mixed Integer Linear Programming

We describe this problem as a mixed integer linear program that is modeled in the python-mip library. This library helps formulate mixed integer programs for the free solver CBC. Using Python is also helpful as its 

In mixed integer programming we model a problem as an objective to minimise (or maximise) and a set of constraints. For our mixed integer linear program, we have

We begin with loading in the data and the packages and creating a model object. 
The data contains each 
```{python python.reticulate = FALSE,results ='asis'}
from mip import *
import json

with open("./data/set_7/set_7_data.json", "r") as f:
    data = json.loads(f.read())
    
data["trait_levels"] = list(map(tuple, data["trait_levels"]))

model = Model(solver_name=CBC)
model.verbose = 0

```

